name: Quality check
on:
  push:
    branches:
    - "*"
  pull_request:

permissions:
  contents: read

jobs:
  static-analysis:
    name: Tests & Static analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            git.io:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup seccomp
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1.4.3
        with:
          packages: libseccomp-dev

      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: make

      - run: make check
