name: Publish
on:
  push:
    tags:
      - 'cli/v*'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            git.io:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            sum.golang.org:443
            ppa.launchpadcontent.net:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 'stable'

      - name: Setup seccomp
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1.4.3
        with:
          packages: libseccomp-dev

      - name: Install dependencies
        run: make

      - run: make dist

      - name: Save build artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: binaries
          path: dist/
          retention-days: 14
          if-no-files-found: error

  release:
    needs: build

    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            uploads.github.com:443

      - name: Extract build artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: binaries

      - name: Prepare release
        uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
        with:
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "*"
